name: 'DuploCloud Finish Release'
description: 'Finishes a gitflow release'
author: 'DuploCloud, Inc.'
inputs:
  github_token:
    required: true
    description: 'Github token to use for pushing the tag and deleting the release branch'
  target_ref:
    required: false
    description: 'release target ref (pull request base ref - defaults to {{ github.base_ref }}, which is usually master)'
    default: ''
  source_ref:
    required: false
    description: 'release source ref (pull request head ref - defaults to {{ github.head_ref }})'
    default: ''
  develop_ref:
    required: false
    description: 'develop ref (defaults to develop)'
    default: 'develop'
  tag_prefix:
    required: false
    description: 'The tag prefix (defaults to "v")'
    default: 'v'
  delete_branch:
    required: false
    description: 'Whether or not to delete the release branch.'
    default: 'true'
  validate_merge:
    required: false
    description: 'Validates that the source_ref was already merged into the target_ref.  Set this to "false" if you merge a squashed commit.'
    default: 'true'
outputs:
  release_tag:
    description: release git tag (with version prefix)
    value: "${{ steps.validate.outputs.release_tag }}"
  release_branch:
    description: release git branch
    value: "${{ steps.validate.outputs.release_branch }}"
  release_commit:
    description: release git commit
    value: "${{ steps.validate.outputs.release_commit }}"
  source_ref:
    description: release source ref (pull request head)
    value: "${{ steps.validate.outputs.source_ref }}"
  target_ref:
    description: release target ref (pull request base)
    value: "${{ steps.validate.outputs.target_ref }}"
runs:
  using: 'composite'
  steps:
    # VALIDATION:  This check validates that the release has already been merged into master.
    #   - It also creates an "output" identifying the release commit.
    - id: validate
      shell: bash
      run: |
        # Fail on errors, and strictly interpret shell code
        set -eu

        # Get the target ref.
        [ -z "$TARGET_REF" ] && TARGET_REF="${{ github.base_ref }}"
        [ -z "$TARGET_REF" ] && TARGET_REF="master"

        # Get the source ref.
        [ -z "$SOURCE_REF" ] && SOURCE_REF="${{ github.head_ref }}"
        [ -z "$SOURCE_REF" ] && SOURCE_REF="$(git rev-parse --abbrev-ref HEAD)"

        # Get the release commit
        if [ "$VALIDATE_MERGE" = "true" ]
        then git checkout "$SOURCE_REF"
        else git checkout "$TARGET_REF"
        fi

        # Identity the release version and the target git commit
        RELEASE_VERSION="${SOURCE_REF##*/}"
        RELEASE_TAG="${{ inputs.tag_prefix }}$RELEASE_VERSION"
        RELEASE_COMMIT="$(git rev-parse HEAD)"

        # Validate that the release commit exists in the target ref
        if [ "$VALIDATE_MERGE" = "true" ] && ! git merge-base --is-ancestor "$RELEASE_COMMIT" "$TARGET_REF"; then
          echo "::error cannot finish the release: the release must already be merged into '$TARGET_REF' branch"
          exit 1
        fi
        
        # Checkout the target ref again, and output the release ref, tag and commit
        git checkout "$TARGET_REF"
        echo "source_ref=$SOURCE_REF" >> $GITHUB_OUTPUT
        echo "target_ref=$TARGET_REF" >> $GITHUB_OUTPUT
        echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        echo "release_commit=$RELEASE_COMMIT" >> $GITHUB_OUTPUT
      env:
        VALIDATE_MERGE: "${{ inputs.validate_merge }}"
        SOURCE_REF: "${{ inputs.source_ref }}"
        TARGET_REF: "${{ inputs.target_ref }}"

    # PUSH RELEASE TO GIT
    - id: tag-release
      shell: bash
      run: |
        git tag "$RELEASE_TAG"
      env:
        RELEASE_TAG: "${{ steps.validate.outputs.release_tag }}"
    - name: Push tag
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ steps.validate.outputs.target_ref }}
        tags: true

    # START NEXT DEVELOP ITERATION:
    #   - Checkout develop.
    #   - Merge master back into develop.
    #   - Push develop.
    - id: checkout-develop
      uses: actions/checkout@v4
      with:
        ref: "${{ inputs.develop_ref }}"
        fetch-depth: 0              # Workaround to allow merging from origin/master
        persist-credentials: false  # Needed so we can push with different credentials.
                                    # NOTE: Pushing with different credentials allows admins to push protected branches.
                                    # NOTE: Pushing with different credentials allow workflows to trigger from the push.
    - id: merge-develop
      shell: bash
      run: |
        git merge origin/${{ steps.validate.outputs.target_ref }} --no-edit
    - uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: develop
        tags: true

    # CLEAN UP RELEASE BRANCH
    - name: Delete branch
      if: ${{ inputs.delete_branch == 'true' }}
      shell: bash
      run: |
        sudo apt-get install -y gh
        gh api -X DELETE "repos/${GITHUB_REPOSITORY}/git/refs/heads/${{ steps.validate.outputs.source_ref }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
